# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltReviewer', '0004_auto_20180224_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
    ]
